# Site settings
title: Paulius Riauka
name: Paulius Riauka

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: GitHub
   url: https://github.com/pauliusriauka
 - title: LinkedIn
   url: https://www.linkedin.com/in/paulius-riauka-721004152/

#Any buzzword skills you want to include
skills:
 - C++
 - C
 - Embedded systems
 - Digital signal processing
 - Real-time programming
 - Version control
 - Python
 - MATLAB/ Simulink
 - Digital design
 - Analog design
 - 3D modelling
 - Soldering
 - Debugging
 - Test automation
 - LaTeX

#Education is required
education:
 - level: Bachelor of Science (B.Sc.)
   date: 2020
   subject: Electronics and Computer Engineering
   school: Aalborg University

#Work experience is required
roles:
 - title: Runner
   start: 2019
   end: 2020
   employer: Heidi's Bier Bar Aarhus
   description: Part-time student job that turned into a hobbie. It introduced me to a social Danish working environment as well as helped me get practice my language skills. 
 - title: Active member
   start: 2019
   end: 2022
   employer: Open Space Aarhus
   description: Started an active membeship to have access to a workshop for personal electronics projects as well as new tools to expand my field of knowledge. 
 - title: Newspaper distributor
   start: 2017
   end: 2019
   employer: FK distribution
   description: This job has introuced me to the Danish tax system as well as work ethics.


#List of interesting Github repo/projects to include - optional
github:
 - PauliusRiauka/PauliusRiauka.github.io
 - PauliusRiauka/attiny85-lighting-system
 - PauliusRiauka/Frequency-based-event-detector

intro: |
  I am a fresh engineering graduate with passion towards signal processing, embedded real-time systems and consumer electronics.
  I value continuous learning and social networking. To improve myself in both of these fields I attend Open Space Aarhus' events as well as Danish language classes. 
  
#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
   <strong>C++</strong>: This programming language has been my first programming tool as well as my generally preferred tool for the past five years. I have used this language to create numerous projects for university related tasks as well as personal projects.<br/><br/>
   <strong>C</strong>: I have been exercising this language for the past three years with an ambition to have as complete control of the program execution speed as possible without sacrifising the <br/><br/>
   <strong>Python</strong> I have found this language very useful during an attempt to use Raspberry Pi as a microcontroller for an embedded system. This has given be great basics of the language and it's use cases.<br/><br/>
   <strong>MATLAB/ Simulink</strong>: These programs have proven to be a very valuable tool to easily asess feasibility of a hypothesis and therefore were used for nearly every university related project throughout my studies. <br/><br/>
   <strong>3D modelling</strong>: This field of technology together with 3D printing has caught my eye as a way to finish up personal electronics projects with casing. I plan to further exapnd my knowledge in this field to explore the capabilities of my creativity.<br/><br/>
   <strong>Development Control</strong>: I have the basic knowledge of application life-cycle management and have worked with Git.<br/><br/>
   Currently I am learning how to operate various Atmel microcontrollers though AVR ISP mkii programmer using Atmel Studio, android app development, expanding my circuit design and soldering skills.
theme: jekyll-theme-slate
